{
 "title": "Langfuse",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pods",
    "label": "pods",
    "query": {
     "query": "label_values({namespace=\"mod-langfuse-dev\", pod!=\"langfuse-zookeeper-0\", pod!=\"langfuse-zookeeper-1\", pod!=\"langfuse-zookeeper-2\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod / Container status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod restart",
   "type": "timeseries",
   "description": "จำนวนที่ pod restart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"mod-langfuse-dev\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "$pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "pods" },
  {
   "title": "CPU Usage (percentage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pods\"}[$__rate_interval])) by (pod) \n/\nsum (kube_pod_container_resource_limits{pod=~\"$pods\",resource=\"cpu\"}) by (pod)\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage by limit (percentage)",
   "type": "timeseries",
   "description": "% การใช้ memory เทียบกับ limit",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$pods\", id=~\".*slice\"}) by (pod)\n/\nsum(kube_pod_container_resource_limits{namespace=\"mod-langfuse-dev\", pod=~\"$pods\",resource=\"memory\"}) by (pod)\n* 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage by request (percentage)",
   "type": "timeseries",
   "description": "Memory Usage % เทียบกับ Request -> ใช้ดู memory เกิน request หรือยัง",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$pods\", id=~\".*slice\"}) by (pod)\n/\nsum(kube_pod_container_resource_requests{pod=~\"$pods\", resource=\"memory\"}) by (pod)\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk capacity",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*$pods.*\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Disk usage (percentage)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 26 },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*$pods.*\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*$pods.*\"} * 100",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Disk available ",
   "type": "timeseries",
   "description": "disk ที่เหลือให้ใช้",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 26 },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*$pods.*\"} \n-\nkubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*$pods.*\"} ) / 1024 / 1024 / 1024",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}